{% set name = "cvxpy" %}
{% set version = "1.0.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e5a80c49f0d735e7a13b6fbc259f856df82e8d9708799cb1b8bc50b4532f4518

build:
  number: 0
  skip: true  # solvers are missing on:  # [win]

# Need these up here for conda-smithy to handle them properly.
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
  run:
    - python

outputs:
  - name: cvxpy
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('cvxpy-base', exact=True) }}
        - osqp
        - ecos >=2
        - scs >=1.1.3
    test:
      imports:
        - cvxpy
        - cvxpy.cvxcore
        - cvxpy.cvxcore.python
      requires:
        - nose
      commands:
        - nosetests cvxpy
  - name: cvxpy-base
    build:
      script: "{{ PYTHON }} -m pip install . --no-deps -vvv"
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - python
        - numpy 1.14
        - pip
      run:
        - python
        - {{ pin_compatible('numpy') }}
        - scipy >=1.1.0
        - multiprocess
        - fastcache
        - six
    test:
      imports:
        - cvxpy
        - cvxpy.cvxcore
        - cvxpy.cvxcore.python

about:
  home: http://www.cvxpy.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'A Python-embedded modeling language for convex optimization problems'
  description: |
    CVXPY is a Python-embedded modeling language for convex optimization
    problems. It allows you to express your problem in a natural way that
    follows the math, rather than in the restrictive standard form required
    by solvers.
  doc_url: http://www.cvxpy.org/
  dev_url: https://github.com/cvxgrp/cvxpy

extra:
  recipe-maintainers:
    - dougalsutherland
    - mcg1969
