{% set version = "1.6.4" %}

package:
  name: cvxpy-split
  version: {{ version }}

source:
  url: https://github.com/cvxpy/cvxpy/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 34dcc49691ef9021b76c8f9556bbb236c0abfaa0ad6f0d3f7967fc12c80ae25f
  patches:
    # test that fails due to timing issues on slow CI agents when in emulation
    - patches/0001-loosen-time-limit-in-test_scipy_mi_time_limit_reache.patch

build:
  number: 0
  # debugging segfaults in test suite
  skip: true  # [not osx]

outputs:
  - name: cvxpy
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('cvxpy-base', exact=True) }}
        - osqp >=0.6.2
        - clarabel >=0.5
        - scs >=3.2.4
    test:
      requires:
        - pip
        - pytest
        - cvxopt
        - hypothesis
        # cvxopt appears to have issues with newer scipy
        - scipy <1.15
      source_files:
        - cvxpy/tests
      imports:
        - cvxpy
        - cvxpy.cvxcore
        - cvxpy.cvxcore.python
      commands:
        {% set tests_to_skip = "_not_a_real_test" %}
        # accuracy failure on PPC, likely due to emulation
        {% set tests_to_skip = tests_to_skip + " or (TestDqcp and test_basic_multiply) " %}     # [ppc64le]
        {% set tests_to_skip = tests_to_skip + " or test_sparsity_condition " %}                # [py==313]
        - pytest --capture=sys cvxpy/tests -v -k "not ({{ tests_to_skip }})"
        # test that pip recognizes installation correctly, see https://github.com/cvxpy/cvxpy/issues/2389;
        # 'grep -v' inverts the match but returns non-zero exit code if no lines are returned; so we use 'wc -l';
        - if [ 0 -eq $(pip list | grep "UNKNOWN" | wc -l) ]; then exit 0; else (pip list && exit 1); fi  # [unix]

  - name: cvxpy-base
    build:
      script:
        - rm $SRC_DIR/pyproject.toml    # [unix]
        - del %SRC_DIR%\pyproject.toml  # [win]
        - python -m pip install . --no-deps -vvv
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
      host:
        - python
        - pybind11
        # conda-forge recipe inserts oldest numpy per platform/runtime
        - numpy
        - pip
        - setuptools
      run:
        - python
        - scipy >=1.1.0
    test:
      imports:
        # public interface is defined (see #75) to be the content of
        # https://github.com/cvxpy/cvxpy/blob/master/cvxpy/__init__.py
        - cvxpy

about:
  home: http://www.cvxpy.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A Python-embedded modeling language for convex optimization problems
  description: |
    CVXPY is a Python-embedded modeling language for convex optimization
    problems. It allows you to express your problem in a natural way that
    follows the math, rather than in the restrictive standard form required
    by solvers.
  doc_url: http://www.cvxpy.org/
  dev_url: https://github.com/cvxpy/cvxpy

extra:
  recipe-maintainers:
    - timkpaine
    - SteveDiamond
    - akshayka
    - rileyjmurray
    - djsutherland
    - mcg1969
    - scopatz
    - h-vetinari
  feedstock-name: cvxpy
