{% set name = "cvxpy" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9d6d6e315cbf6ec9063feac64c083758e6486a384a9143df5c281ad07f65087b
  patches:
    - patches/0001-remove-pyproject.toml.patch

build:
  number: 0
  skip: true  # [py==27 and win]
  skip: true  # [py==27 and not x86_64]

# Need these up here for conda-smithy to handle them properly.
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
  run:
    - python

outputs:
  - name: cvxpy
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('cvxpy-base', exact=True) }}
        - osqp
        - ecos >=2
        - scs >=1.1.3
    test:
      imports:
        - cvxpy
        - cvxpy.cvxcore
        - cvxpy.cvxcore.python
      requires:
        - nose
      commands:
        - nosetests cvxpy
  - name: cvxpy-base
    build:
      script: {{ PYTHON }} -m pip install . --no-deps -vvv
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - python
        # conda-forge recipe inserts oldest numpy per platform/runtime
        - numpy
        - pip
      run:
        - python
        - {{ pin_compatible('numpy') }}
        - scipy >=1.1.0
        - multiprocess
        - six
    test:
      imports:
        - cvxpy
        - cvxpy.cvxcore
        - cvxpy.cvxcore.python

about:
  home: http://www.cvxpy.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A Python-embedded modeling language for convex optimization problems
  description: |
    CVXPY is a Python-embedded modeling language for convex optimization
    problems. It allows you to express your problem in a natural way that
    follows the math, rather than in the restrictive standard form required
    by solvers.
  doc_url: http://www.cvxpy.org/
  dev_url: https://github.com/cvxgrp/cvxpy

extra:
  recipe-maintainers:
    - SteveDiamond
    - akshayka
    - rileyjmurray
    - djsutherland
    - mcg1969
    - scopatz
    - h-vetinari
