{% set name = "cvxpy" %}
{% set version = "1.5.1" %}

package:
  name: cvxpy-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 225c90abe61a143dde2ff72d1acf9875b58d8c047ad589abc1b735640735dbfc

build:
  number: 0

# Need these up here for conda-smithy to handle them properly.
requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
  run:
    - python

outputs:
  - name: cvxpy
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('cvxpy-base', exact=True) }}
        - osqp >=0.6.2
        - clarabel >=0.5
        - ecos >=2
        - scs >=3.0
    test:
      requires:
        - pytest
        - cvxopt
      source_files:
        - cvxpy/tests
      imports:
        - cvxpy
        - cvxpy.cvxcore
        - cvxpy.cvxcore.python
      commands:
        - pytest cvxpy/tests -v

  - name: cvxpy-base
    build:
      script:
        - rm $SRC_DIR/pyproject.toml    # [unix]
        - del %SRC_DIR%\pyproject.toml  # [win]
        - {{ PYTHON }} -m pip install . --no-deps -vvv
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
      host:
        - python
        - pybind11
        # conda-forge recipe inserts oldest numpy per platform/runtime
        - numpy
        - pip
      run:
        - python
        - {{ pin_compatible('numpy') }}
        - scipy >=1.1.0
    test:
      imports:
        # public interface is defined (see #75) to be the content of
        # https://github.com/cvxpy/cvxpy/blob/master/cvxpy/__init__.py
        - cvxpy

about:
  home: http://www.cvxpy.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A Python-embedded modeling language for convex optimization problems
  description: |
    CVXPY is a Python-embedded modeling language for convex optimization
    problems. It allows you to express your problem in a natural way that
    follows the math, rather than in the restrictive standard form required
    by solvers.
  doc_url: http://www.cvxpy.org/
  dev_url: https://github.com/cvxpy/cvxpy

extra:
  recipe-maintainers:
    - timkpaine
    - SteveDiamond
    - akshayka
    - rileyjmurray
    - djsutherland
    - mcg1969
    - scopatz
    - h-vetinari
  feedstock-name: cvxpy
