travis:
  secure:
    BINSTAR_TOKEN: nweLm+iqVUNanR6nzDulPucpoo35HxCpRCbRwlKZKLSItzTAWH5VKxmGXkcG+krbneNqmjIBj84KPnuhvtMoMzj1NqEm/RyU+ETYFoX39J9UAg6OC4gqTRfAGTi/+pm3ocDliGp1yQeG4UrRKMJ0HFQzHmzO7WBtNW1iYEqVoHPCo/O5RnMvfwwD5T+lzIhEB68eKIu7aakkEgHOJ3ee2gNjSweonw0vUf5HPW2ekJlfd5P0q+Rn0YSI5iQQg6yUsp6CmiXb1so9v6WNwF08h2pQWP3b9EhN5oFscEyfUrm6nxWGseRNzB1Z50OymW7p4los36RsswZEf7QzQSBRcb79tLj2jx9iQAWsGCLihGSb5tdP7bTcgW5NbqNXk49btkHbVRnW0S2NIFeyfro9zYjFwLJhHldCrd6/sEHL37PqaPkczrh7zUP8D7Gekvt+3Z2hjHm1K0D2m7GUPvj1fM60i6mitBTXF7+YsED3s/Mp9zNfTiJcD1+eMWWe0U3qkTBX93ujAC2y/8xixry+zEHYdDALg0VzNIXOc+wO4C2G8Rqa0omdR/FB+eq4QD8i44GWG8i6EozWKnC4mUHNNWOgvwM/k1GVUdRxWIgNpCsVPyCZG6qyBuAQGfBDSLUBL/vO/I7MIVB5UL56mqfJp1RRe6FwY+VBc/X2fcob71k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
